package com.example.ui.components

import android.content.Intent
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.model.ExamResultEntity
import com.example.data.model.StudentEntity

@Composable
fun ReportCardView(
    student: StudentEntity,
    examResults: List<ExamResultEntity>,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var selectedTab by remember { mutableStateOf("Monthly") } // "Monthly" or "Annual"

    val filteredResults = remember(examResults, selectedTab) {
        if (selectedTab == "Monthly") {
            examResults.filter { it.examType.contains("Monthly", ignoreCase = true) }
        } else {
            examResults.filter { it.examType.contains("Annual", ignoreCase = true) }
        }
    }

    val totalMarks = filteredResults.sumOf { it.marksObtained }
    val totalMax = filteredResults.sumOf { it.maxMarks }.takeIf { it > 0 } ?: 1
    val percentage = (totalMarks.toDouble() / totalMax.toDouble()) * 100.0
    val overallGrade = when {
        percentage >= 90 -> "A+"
        percentage >= 80 -> "A"
        percentage >= 70 -> "B+"
        percentage >= 60 -> "B"
        percentage >= 50 -> "C"
        else -> "D"
    }

    Card(
        modifier = modifier
            .fillMaxWidth()
            .testTag("report_card_view"),
        shape = RoundedCornerShape(20.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(20.dp)
        ) {
            // Header
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(
                        Icons.Default.School,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.size(24.dp)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "Official Academic Report Card",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                }

                FilledTonalButton(
                    onClick = {
                        val reportSummary = buildString {
                            appendLine("===== ACADEMIC REPORT CARD =====")
                            appendLine("School: ${student.schoolName}")
                            appendLine("Student: ${student.name}")
                            appendLine("Class: ${student.className}-${student.section} | Roll: ${student.rollNumber}")
                            appendLine("Exam Type: $selectedTab Exam")
                            appendLine("--------------------------------")
                            filteredResults.forEach {
                                appendLine("${it.subject}: ${it.marksObtained}/${it.maxMarks} (Grade: ${it.grade})")
                            }
                            appendLine("--------------------------------")
                            appendLine("Total: $totalMarks / $totalMax (${String.format("%.1f", percentage)}%)")
                            appendLine("Overall Grade: $overallGrade")
                            appendLine("Generated by School Portal on ${java.time.LocalDate.now()}")
                        }
                        val shareIntent = Intent(Intent.ACTION_SEND).apply {
                            type = "text/plain"
                            putExtra(Intent.EXTRA_SUBJECT, "Report Card - ${student.name}")
                            putExtra(Intent.EXTRA_TEXT, reportSummary)
                        }
                        context.startActivity(Intent.createChooser(shareIntent, "Export / Share Report Card"))
                    },
                    modifier = Modifier.testTag("btn_export_report_card")
                ) {
                    Icon(Icons.Default.PictureAsPdf, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Export / Share")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Tab Selector: Monthly vs Annual
            TabRow(
                selectedTabIndex = if (selectedTab == "Monthly") 0 else 1,
                containerColor = MaterialTheme.colorScheme.surfaceVariant,
                modifier = Modifier.clip(RoundedCornerShape(12.dp))
            ) {
                Tab(
                    selected = selectedTab == "Monthly",
                    onClick = { selectedTab = "Monthly" },
                    text = { Text("Monthly Exams") },
                    modifier = Modifier.testTag("tab_monthly_exams")
                )
                Tab(
                    selected = selectedTab == "Annual",
                    onClick = { selectedTab = "Annual" },
                    text = { Text("Annual Exams") },
                    modifier = Modifier.testTag("tab_annual_exams")
                )
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Score Banner
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(12.dp))
                    .background(MaterialTheme.colorScheme.primaryContainer)
                    .padding(16.dp),
                horizontalArrangement = Arrangement.SpaceAround,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text(
                        text = "$totalMarks / $totalMax",
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                    Text(
                        text = "Total Marks",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                }

                Box(
                    modifier = Modifier
                        .height(36.dp)
                        .width(1.dp)
                        .background(MaterialTheme.colorScheme.outlineVariant)
                )

                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text(
                        text = "${String.format("%.1f", percentage)}%",
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = "Percentage",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                }

                Box(
                    modifier = Modifier
                        .height(36.dp)
                        .width(1.dp)
                        .background(MaterialTheme.colorScheme.outlineVariant)
                )

                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Surface(
                        shape = RoundedCornerShape(8.dp),
                        color = Color(0xFF16A34A)
                    ) {
                        Text(
                            text = overallGrade,
                            modifier = Modifier.padding(horizontal = 12.dp, vertical = 2.dp),
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                            color = Color.White
                        )
                    }
                    Text(
                        text = "Grade",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            if (filteredResults.isEmpty()) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(24.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text(
                        text = "No $selectedTab exam results published yet.",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            } else {
                // Table of Subjects
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(12.dp))
                        .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(12.dp))
                ) {
                    // Table Header
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(MaterialTheme.colorScheme.surfaceVariant)
                            .padding(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Subject", modifier = Modifier.weight(2f), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelMedium)
                        Text("Marks", modifier = Modifier.weight(1.2f), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelMedium)
                        Text("Grade", modifier = Modifier.weight(1f), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelMedium)
                        Text("Performance", modifier = Modifier.weight(1.5f), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelMedium)
                    }

                    filteredResults.forEachIndexed { index, result ->
                        val subPct = (result.marksObtained.toFloat() / result.maxMarks.toFloat()).coerceIn(0f, 1f)
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(if (index % 2 == 0) MaterialTheme.colorScheme.surface else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f))
                                .padding(12.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(modifier = Modifier.weight(2f)) {
                                Text(
                                    text = result.subject,
                                    fontWeight = FontWeight.Medium,
                                    style = MaterialTheme.typography.bodyMedium
                                )
                                if (result.remarks.isNotBlank()) {
                                    Text(
                                        text = result.remarks,
                                        style = MaterialTheme.typography.bodySmall,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                                        fontSize = 11.sp
                                    )
                                }
                            }

                            Text(
                                text = "${result.marksObtained} / ${result.maxMarks}",
                                modifier = Modifier.weight(1.2f),
                                style = MaterialTheme.typography.bodyMedium,
                                fontWeight = FontWeight.SemiBold
                            )

                            Surface(
                                shape = RoundedCornerShape(4.dp),
                                color = when (result.grade) {
                                    "A+" -> Color(0xFF16A34A).copy(alpha = 0.2f)
                                    "A" -> Color(0xFF2563EB).copy(alpha = 0.2f)
                                    "B+", "B" -> Color(0xFFD97706).copy(alpha = 0.2f)
                                    else -> Color.Gray.copy(alpha = 0.2f)
                                }
                            ) {
                                Text(
                                    text = result.grade,
                                    modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp),
                                    fontWeight = FontWeight.Bold,
                                    style = MaterialTheme.typography.labelMedium,
                                    color = MaterialTheme.colorScheme.onSurface
                                )
                            }

                            Spacer(modifier = Modifier.width(8.dp))

                            LinearProgressIndicator(
                                progress = { subPct },
                                modifier = Modifier
                                    .weight(1.5f)
                                    .height(8.dp)
                                    .clip(RoundedCornerShape(4.dp)),
                                color = when {
                                    subPct >= 0.85f -> Color(0xFF16A34A)
                                    subPct >= 0.70f -> Color(0xFF2563EB)
                                    subPct >= 0.50f -> Color(0xFFD97706)
                                    else -> Color(0xFFDC2626)
                                }
                            )
                        }
                    }
                }
            }
        }
    }
}
